### ISSUE TITLE
Tests Aspect a Little Weird

### ISSUE THREAD

**Issue by ddbrennan** [learn-co-curriculum/has-many-through-forms-rails#15]
I might have missed something, but all I did was add the one line of "accepts nested..." and then delete the automatically generated test files. Am I supposed to create tests? Should those have even been there? Is this just meant to be a read me?

**Comment by drakeltheryuujin** [comment]
Thanks for reporting this issue. We're now aware of it and are tracking it in
issue #25 .

We will add this to our internal work queue. We are in the process of updating
the materials in this section and will be rewriting this lesson to address the
current issues. We'll be taking all of this information into consideration in
upcoming releases of this curriculum.

We're closing this issue but invite you to follow the progress. We will notify
you when it is resolved.

Thanks for contributing!
