### ISSUE TITLE
Last Code Snippet

### ISSUE THREAD

**Issue by jamiegiuliano** [learn-co-curriculum/has-many-through-forms-rails#16]
It might be a little less confusing if on the last code snippet the 'accepts_nested_attributes_for :categories' macro was deleted or commented out when the custom 'categories_attributes=' method is there.

**Comment by drakeltheryuujin** [comment]
Thanks for reporting this issue. We're now aware of it and are tracking it in
issue #25 .

We will add this to our internal work queue. We are in the process of updating
the materials in this section and will be rewriting this lesson to address the
current issues. We'll be taking all of this information into consideration in
upcoming releases of this curriculum.

We're closing this issue but invite you to follow the progress. We will notify
you when it is resolved.

Thanks for contributing!
