### ISSUE TITLE
Re; lab

### ISSUE THREAD

**Issue by eyosef** [learn-co-curriculum/has-many-through-forms-rails#17]
Would the staff consider creating an easier lab prior to this lab? This lab has a lot of moving parts and I found it to be confusing. It really obscured the learning process for me. I think having an easier lab precede this lab would allow students to better grapple with the topic.

**Comment by drakeltheryuujin** [comment]
Thanks for reporting this issue. We're now aware of it and are tracking it in
issue #25 .

We will add this to our internal work queue. We are in the process of updating
the materials in this section and will be rewriting this lesson to address the
current issues. We'll be taking all of this information into consideration in
upcoming releases of this curriculum.

We're closing this issue but invite you to follow the progress. We will notify
you when it is resolved.

Thanks for contributing!
