### ISSUE TITLE
No learn tests

### ISSUE THREAD

**Issue by Hector-Ariceaga** [learn-co-curriculum/has-many-through-forms-rails#20]
The only tests in this lab are pending templates from the rails generator.

Fixes include:
1) delete rails MiniTest default tests
2) make lab a code along
3) add tests to confirm has_many :through relationship

**Comment by drakeltheryuujin** [comment]
Thanks for reporting this issue. We're now aware of it and are tracking it in
issue #25 .

We will add this to our internal work queue. We are in the process of updating
the materials in this section and will be rewriting this lesson to address the
current issues. We'll be taking all of this information into consideration in
upcoming releases of this curriculum.

We're closing this issue but invite you to follow the progress. We will notify
you when it is resolved.

Thanks for contributing!
