### ISSUE TITLE
Can't submit lesson with no test

### ISSUE THREAD

**Issue by JoeQuattrone** [learn-co-curriculum/has-many-through-forms-rails#21]
I ran the tests and 2 were pending, but that counts as failing to Learn. I then deleted the specs and submitted it, but it's saying my lesson is incomplete because I failed the tests from before. Now I have to make a fake test and pass it just to complete this lesson

**Comment by BebopVinh** [comment]
Issue still remains. I did a workaround running `rails g rspec:install`, replaced the '.rspec' file, then running `learn`.

**Comment by Marie-Burns22** [comment]
Hi, I also am having a similar issue with this lesson/lab.  I'm using the local environment and was able to fork it and submit it and both turned green. However,  this lesson has "run local tests" that needs to turn green, but I get this error when I run `learn` in the terminal. "This directory doesn't appear to have any specs in it."  

I do not see a spec folder.

I used the workaround posted by BebopVihn and that worked.

**Comment by FreeBreadsticks** [comment]
@drakeltheryuujin Hello again, it appears this lesson has a similar issue to the lab I just tagged you in. Looks like this lesson expects tests to run but there are no tests built into the lab itself.

**Comment by drakeltheryuujin** [comment]
Thanks for reporting this issue. We're now aware of it and are tracking it in
issue #25 .

We will add this to our internal work queue. We are in the process of updating
the materials in this section and will be rewriting this lesson to address the
current issues. We'll be taking all of this information into consideration in
upcoming releases of this curriculum.

We're closing this issue but invite you to follow the progress. We will notify
you when it is resolved.

Thanks for contributing!
