### ISSUE TITLE
Must create fake test

### ISSUE THREAD

**Issue by taoliu12** [learn-co-curriculum/has-many-through-forms-rails#22]
Must fake a test.rb file.
1. rename test folder to spec
2. create dummy test.rb file in models test folder

**Comment by taoliu12** [comment]
#dummy test


require "test_helper"

describe "Song" do

  describe "#initialize" do
    it "accepts a name for the new song" do
      
    end
  end

**Comment by drakeltheryuujin** [comment]
Thanks for reporting this issue. We're now aware of it and are tracking it in
issue #25 .

We will add this to our internal work queue. We are in the process of updating
the materials in this section and will be rewriting this lesson to address the
current issues. We'll be taking all of this information into consideration in
upcoming releases of this curriculum.

We're closing this issue but invite you to follow the progress. We will notify
you when it is resolved.

Thanks for contributing!
