### ISSUE TITLE
Temporary Fix for Tests

### ISSUE THREAD

**Issue by dwyn** [learn-co-curriculum/has-many-through-forms-rails#23]
1. $ `rails g rspec:install`

When prompted to overwrite has-many-through-forms-rails/.rspec? (enter "h" for help) [Ynaqdhm], type `y`

**Comment by helloamandamurphy** [comment]
This worked! Thanks, Dwayne!

**Comment by drakeltheryuujin** [comment]
Thanks for reporting this issue. We're now aware of it and are tracking it in
issue #25 .

We will add this to our internal work queue. We are in the process of updating
the materials in this section and will be rewriting this lesson to address the
current issues. We'll be taking all of this information into consideration in
upcoming releases of this curriculum.

We're closing this issue but invite you to follow the progress. We will notify
you when it is resolved.

Thanks for contributing!
