### ISSUE TITLE
No Specs in Test

### ISSUE THREAD

**Issue by donnovan-lyons** [learn-co-curriculum/has-many-through-forms-rails#26]
I'm unable to complete the lab because there are no specs in it. Is it possible to change it to just a pull request lab type?

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
