### ISSUE TITLE
Temporary Fix for lack of spec

### ISSUE THREAD

**Issue by BenitolSantos** [learn-co-curriculum/has-many-through-forms-rails#27]
Must fake a test.rb and change test_helper.rb to spec_helper.rb file.

rename test folder to spec
create dummy test.rb file in models test folder

#dummy test

require "spec_helper"

describe "Song" do

describe "#initialize" do
it "accepts a name for the new song" do

end
end

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
