### ISSUE TITLE
There are no local tests. But they are required to move on.

### ISSUE THREAD

**Issue by thistonyb** [learn-co-curriculum/has-many-through-forms-rails#28]
This lesson requires a fork, local tests, and submit. However there are no local tests to make it turn green before moving on to the next lesson.

**Comment by levimllr** [comment]
Ditto!

**Comment by Allenfp** [comment]
Bump

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
