### ISSUE TITLE
Lab doesn't have Rspec's spec directory, though Learn.co website is expecting Tests

### ISSUE THREAD

**Issue by jrodden1** [learn-co-curriculum/has-many-through-forms-rails#29]
When I completed following through on this lab, I ran `learn` to check on the tests, but received the following error:

```
// $ learn 
This directory doesn't appear to have any specs in it.
```
I then double checked the learn.co page and it said there were supposed to be tests for this lab:
![image](https://user-images.githubusercontent.com/39208179/63612833-7af5a600-c59c-11e9-9e4c-b208a890a6da.png)

I then checked my repo for a `spec` directory, but there doesn't seem to be one - rather it has a fairly empty `test` directory instead. 
![image](https://user-images.githubusercontent.com/39208179/63612813-65807c00-c59c-11e9-9e9b-427005d148f7.png)

When I tried to continue past this by pressing the 'Next Lesson' button, but I got a big scary-gram message saying that I really needed to complete the lesson before continuing... 

So, I went ahead and ran `rails generate rspec:install` to create the spec directory and then ran `learn` -- the tests showed as passing (0 examples, 0 failures).  The Learn.co website then registered the tests were 'passing' now and I was able to continue by pressing the `Next Lesson` button without a scary warning.

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
